name: Build Frontend

on:
  push:
    paths: ["apps/frontend/**"]
    branches-ignore:
      - 'refs/tags/*' # In this demo we use tags to simulate what SW is running, so ignore

env:
  # kosli commands picks up org, flow, trail and api-token from these environment variables
  KOSLI_ORG: "${{ vars.KOSLI_ORG }}"
  KOSLI_FLOW: jira-example-frontend
  KOSLI_TRAIL: ${{ github.sha }}
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
  KOSLI_CLI_VERSION: "${{ vars.KOSLI_CLI_VERSION }}"
  KOSLI_TEMPLATE_FILE: "kosli-flow-templates/frontend-template.yml"
  # KOSLI_DRY_RUN: true
  JIRA_BASE_URL: "${{ vars.JIRA_BASE_URL }}"
  JIRA_USERNAME: ${{ secrets.KOSLI_JIRA_USERNAME }}
  JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}

jobs:
  begin-trail:
    name: Begin trail
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Begin trail
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/kosli-begin-trail
        with:
          kosli-trail: ${{ env.KOSLI_TRAIL }}
          kosli-template-file: ${{ env.KOSLI_TEMPLATE_FILE }}

  jira-ticket:
    name: Jira ticket
    needs: [begin-trail]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Attest jira ticket
        uses: ./.github/actions/kosli-attest-jira
        with:
          jira-base-url: ${{ vars.JIRA_BASE_URL }}
          jira-username: ${{ env.JIRA_USERNAME }}
          jira-api-token: ${{ env.JIRA_API_TOKEN }}
          jira-issue-fields: "summary,description"
          report-to-kosli: ${{ github.ref == 'refs/heads/main' }}

  pull-request:
    name: Pull-request
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [begin-trail]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Attest GitHub pull-request
        uses: ./.github/actions/kosli-attest-pullrequest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assert: true

  build:
    name: Build frontend
    needs: [begin-trail]
    runs-on: ubuntu-latest
    outputs:
      fingerprint: ${{ steps.calculate_fingerprint.outputs.fingerprint }}
    steps:
      - uses: actions/checkout@v4

      - name: Build frontend
        run: echo "Here we could do some proper build"

      - name: Extract short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Attest artifact
        id: calculate_fingerprint
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/kosli-attest-dir-artifact
        with:
          kosli-artifact-template-name: frontend
          artifact-name: frontend:${{ env.SHORT_SHA }}
          artifact-dir: apps/frontend

  assert-artifacts:
    name: Assert artifacts
    if: ${{ github.ref == 'refs/heads/main' && always() }}
    needs: [build, jira-ticket, pull-request]
    runs-on: ubuntu-latest
    steps:
      - name: Assert Artifacts
        uses: ./.github/actions/assert-artifacts
        with:
          kosli-environment: ${{ vars.KOSLI_ENV_DEV }}
          fingerprints:  ${{ needs.build.outputs.fingerprint }}

  deploy-dev:
    name: Deploy frontend development
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [build, assert-artifacts]
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to development
        run: echo "Here we could do a proper deploy to Development environment"
