name: Build Backend

on:
  push:
    paths: ["apps/backend/**", ".github/workflows/build-backend.yml"]
    branches-ignore:
      - 'refs/tags/*' # In this demo we use tags to simulate what SW is running, so ignore

env:
  # kosli commands picks up org, flow, trail and api-token from these environment variables
#  KOSLI_ORG: kosli-public
  KOSLI_FLOW: jira-example-backend
  KOSLI_TRAIL: ${{ github.sha }}
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
#  KOSLI_CLI_VERSION: "2.11.8"
  KOSLI_TEMPLATE_FILE: "apps/backend/kosli-template.yml"
  # KOSLI_DRY_RUN: true
#  JIRA_BASE_URL: "https://kosli-team.atlassian.net"
  JIRA_USERNAME: ${{ secrets.KOSLI_JIRA_USERNAME }}
  JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}

jobs:
  begin-trail:
    name: Begin trail
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Begin trail
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/workflows/composites/kosli-begin-trail
        with:
          kosli-trail: ${{ env.KOSLI_TRAIL }}
          kosli-template-file: ${{ env.KOSLI_TEMPLATE_FILE }}

  jira-ticket:
    name: Jira ticket
    needs: [begin-trail]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Attest jira ticket
        uses: ./.github/workflows/composites/kosli-attest-jira
        with:
          jira-base-url: ${{ vars.JIRA_BASE_URL }}
          jira-username: ${{ env.JIRA_USERNAME }}
          jira-api-token: ${{ env.JIRA_API_TOKEN }}
          jira-issue-fields: "summary,description"
          report-to-kosli: ${{ github.ref == 'refs/heads/main' }}

  pull-request:
    name: Pull-request
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [begin-trail]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Attest GitHub pull-request
        uses: ./.github/workflows/composites/kosli-attest-pullrequest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assert: true

  build:
    name: Build backend
    needs: [begin-trail]
    runs-on: ubuntu-latest
    outputs:
      fingerprint: ${{ steps.calculate_fingerprint.outputs.fingerprint }}
    steps:
      - uses: actions/checkout@v4

      - name: Build backend
        run: echo "Here we could do some proper build"

      - name: Extract short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Attest artifact
        id: calculate_fingerprint
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/workflows/composites/kosli-attest-dir-artifact
        with:
          kosli-artifact-template-name: backend
          artifact-name: backend:${{ env.SHORT_SHA }}
          artifact-dir: apps/backend

  assert-artifacts:
    name: Assert artifacts
    if: ${{ github.ref == 'refs/heads/main' && always() }}
    needs: [build, jira-ticket, pull-request]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ vars.KOSLI_CLI_VERSION }}

      - name: Assert Artifacts
        run: |
          set -x
          EXIT_CODE=0
          kosli assert artifact --fingerprint ${{ needs.build.outputs.fingerprint }} || EXIT_CODE=1
          exit ${EXIT_CODE}
          
  deploy-dev:
    name: Deploy backend development
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [build, assert-artifacts]
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to development
        run: echo "Here we could do a proper deploy to Development environment"
