name: Create release

on:
  workflow_dispatch:

env:
  # kosli commands picks up org, flow, trail and api-token from these environment variables
  KOSLI_ORG: kosli-public
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
  KOSLI_CLI_VERSION: "2.11.8"
  # KOSLI_DRY_RUN: true
  JIRA_BASE_URL: "https://kosli-team.atlassian.net"
  JIRA_USERNAME: ${{ secrets.KOSLI_JIRA_USERNAME }}
  JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}
  JIRA_PROJECT_ID: 10000


jobs:
  create-candidate-if-does-not-exist:
    name: Verify no candicate already exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name:
        run: |
          set -x
          source scripts/lib-jira.sh
          current_release_json=$(get_current_release_candidate ${{ env.JIRA_PROJECT_ID }})
          echo "${current_release_json}" | jq .
          current_release=$(echo "${current_release_json}" | jq .values)
          echo cr=$current_release
          if [ "${current_release}" != "[]" ]; then
            echo "Release candidate already exist: ${current_release}"
            exit 1
          fi
          TIMESTAMP=$(date -u "+%Y-%m-%d-%H-%M-%S")
          create_release ${{ env.JIRA_PROJECT_ID }} ${TIMESTAMP} 
