name: Create release

on:
  workflow_dispatch:

env:
  # kosli commands picks up org, flow, trail and api-token from these environment variables
  KOSLI_ORG: kosli-public
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
  KOSLI_CLI_VERSION: "2.11.8"
  KOSLI_ENV_STAGING: "jira-integration-example-staging"
  KOSLI_ENV_PROD: "jira-integration-example-prod"
  KOSLI_FLOW_FRONTEND: "jira-example-frontend"
  KOSLI_FLOW_BACKEND: "jira-example-backend"
  # KOSLI_DRY_RUN: true
  JIRA_BASE_URL: "https://kosli-team.atlassian.net"
  JIRA_USERNAME: ${{ secrets.KOSLI_JIRA_USERNAME }}
  JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}
  JIRA_PROJECT_ID: 10000


jobs:
  create-candidate-if-does-not-exist:
    name: Verify no candicate already exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name:
        run: |
          source scripts/lib-jira.sh
          source scripts/lib-kosli.sh
          
          # Check if a release already exists, if so we fail
#          CURRENT_REL_JSON=$(get_CURRENT_REL_candidate ${{ env.JIRA_PROJECT_ID }})
#          CURRENT_REL=$(echo "${CURRENT_REL_JSON}" | jq .values)
#          if [ "${CURRENT_REL}" != "[]" ]; then
#            echo "Release candidate already exist: ${CURRENT_REL}"
#            exit 1
#          fi

           # Create the release and get the release ID
#          TIMESTAMP=$(date -u "+%Y-%m-%d-%H-%M-%S")
#          CREATE_RESULT_JSON=$(create_release ${{ env.JIRA_PROJECT_ID }} ${TIMESTAMP})
#          RELEASE_ID=$(echo "${CREATE_RESULT_JSON}" | jq .id)
          RELEASE_ID=10099

          # Add jira tickets to release
          JIRA_KEYS=$(get_issue_keys_between_staging_and_prod)
          echo "Found issues: ${JIRA_KEYS}"
          for JIRA_KEY in ${JIRA_KEYS}; do 
            add_issue_to_release ${JIRA_KEY} ${RELEASE_ID}
          done
