name: Create release candidate

on:
  workflow_dispatch:

env:
  # kosli commands picks up org, flow, trail and api-token from these environment variables
  KOSLI_ORG: "${{ vars.KOSLI_ORG }}"
  KOSLI_FLOW: "jira-example-release"
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
  KOSLI_CLI_VERSION: "${{ vars.KOSLI_CLI_VERSION }}"
  KOSLI_ENV_STAGING: "${{ vars.KOSLI_ENV_STAGING }}"
  KOSLI_ENV_PROD: "${{ vars.KOSLI_ENV_PROD }}"
  KOSLI_FLOW_SOURCE: "jira-example-source"
  # KOSLI_DRY_RUN: true
  DEBUG: true
  JIRA_BASE_URL: "${{ vars.JIRA_BASE_URL }}"
  JIRA_USERNAME: ${{ secrets.KOSLI_JIRA_USERNAME }}
  JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}
  JIRA_PROJECT_ID: "${{ vars.JIRA_PROJECT_ID }}"


jobs:
  create-candidate:
    name: Create release candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create Jira release candidate
        run: |          
          source scripts/lib-jira.sh

          # Fail if release already exists
          CURRENT_REL_JSON=$(get_current_release_candidate ${{ env.JIRA_PROJECT_ID }})
          CURRENT_REL=$(echo "${CURRENT_REL_JSON}" | jq .values)
          if [ "${CURRENT_REL}" != "[]" ]; then
            echo "Release candidate already exist: ${CURRENT_REL}"
            exit 1
          fi

          # Create the release and get the release ID
          TIMESTAMP=$(date -u "+%Y-%m-%d-%H-%M-%S")
          CREATE_RESULT_JSON=$(create_release ${{ env.JIRA_PROJECT_ID }} ${TIMESTAMP})
          RELEASE_ID=$(echo "${CREATE_RESULT_JSON}" | jq .id)
          echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV

      - name: Begin trail
        uses: ./.github/actions/kosli-begin-trail
        with:
          kosli-trail: ${{ env.RELEASE_ID }}
#          kosli-template-file: ${{ env.KOSLI_TEMPLATE_FILE }}

      - name: Report current prod SW
        run: |
          source scripts/lib-kosli.sh
          get_current_running_env_json ${{ env.KOSLI_ENV_PROD }} > /tmp/prod-env.json
          create_running_sw_short_list_json /tmp/prod-env.json > /tmp/prod-sw.json

          kosli attest custom \
            --type=running-sw \
            --name prod-software \
            --trail ${{ env.RELEASE_ID }} \
            --attestation-data /tmp/prod-sw.json
          echo "Current prod SW:" >> $GITHUB_STEP_SUMMARY
          cat /tmp/prod-sw.json | jq >> $GITHUB_STEP_SUMMARY

      - name: Report current staging SW
        run: |
          source scripts/lib-kosli.sh
          get_current_running_env_json ${{ env.KOSLI_ENV_STAGING }} > /tmp/staging-env.json
          create_running_sw_short_list_json /tmp/staging-env.json > /tmp/staging-sw.json

          kosli attest custom \
            --type=running-sw \
            --name staging-software \
            --trail ${{ env.RELEASE_ID }} \
            --attestation-data /tmp/staging-sw.json
          echo "Current staging SW:" >> $GITHUB_STEP_SUMMARY
          cat /tmp/staging-sw.json | jq >> $GITHUB_STEP_SUMMARY


      - name: Add Jira issues to release
        run: |          
          source scripts/lib-jira.sh
          source scripts/lib-kosli.sh
          # Add all jira issues between prod and staging
          JIRA_KEYS_IN_KOSLI=$(get_issue_keys_between_staging_and_prod ${KOSLI_ENV_STAGING} ${KOSLI_ENV_PROD} ${KOSLI_FLOW_SOURCE})
          echo "Adding Jira issues: ${JIRA_KEYS_IN_KOSLI}"  >> $GITHUB_STEP_SUMMARY
          for JIRA_KEY in ${JIRA_KEYS_IN_KOSLI}; do
            add_issue_to_release ${JIRA_KEY} ${{ env.RELEASE_ID }}
          done

  
