name: Deploy to Staging

on:
  workflow_dispatch:

env:
  # kosli commands picks up org, flow, trail and api-token from these environment variables
  KOSLI_ORG: kosli-public
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
  KOSLI_CLI_VERSION: "2.11.8"
  KOSLI_ENV_DEV: "jira-integration-example-dev"
  KOSLI_ENV_STAGING: "jira-integration-example-staging"
#  KOSLI_FLOW_FRONTEND: "jira-example-frontend"
#  KOSLI_FLOW_BACKEND: "jira-example-backend"
  # KOSLI_DRY_RUN: true
#  JIRA_BASE_URL: "https://kosli-team.atlassian.net"
#  JIRA_USERNAME: ${{ secrets.KOSLI_JIRA_USERNAME }}
#  JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}
#  JIRA_PROJECT_ID: 10000

jobs:
  deploy-to-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for tagging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ env.KOSLI_CLI_VERSION }}

      - name: Get what SW is running in dev
        run: |
          set -x
          source scripts/lib-kosli.sh
          get_current_running_env_json ${{ env.KOSLI_ENV_DEV }} > /tmp/dev-env.json

      - name: Get frontend tag
        run: |
          COMMIT_SHA=$(jq -r '.[] | select(.name == "frontend") | .git_commit' /tmp/dev-env.json)
          echo "COMMIT_SHA_FRONTEND=$COMMIT_SHA" >> "$GITHUB_ENV"

      - name: Deploy frontend
        # We do not have a real repo so we just tag the git repo and then the
        # simulate-environment-reporting-staging.yml will start reporting that
        # this environment is now running.
        env:
#          GH_TOKEN: ${{ secrets.GH_UPDATE_TAG_TOKEN }}
          OWNER: "kosli-dev"
          REPO: "jira-integration-example"
          TAG: "running-staging-frontend"
        run: |
          API_URL="https://api.github.com/repos/${OWNER}/${REPO}/git/refs/tags/${TAG}"
          
          # Check if the tag exists
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github.v3+json" "${API_URL}")

          if [[ "$STATUS_CODE" == "200" ]]; then
            echo "Tag ${TAG} exists, updating..."
            curl -X PATCH -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github.v3+json" \
              -d "{\"sha\": \"${COMMIT_SHA}\", \"force\": true}" "${API_URL}"
          else
            echo "Tag ${TAG} does not exist, creating..."
            curl -X POST -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github.v3+json" \
              -d "{\"ref\": \"refs/tags/${TAG}\", \"sha\": \"${COMMIT_SHA}\"}" "https://api.github.com/repos/${OWNER}/${REPO}/git/refs"
          fi

#          set -x
#          echo "GH_TOKEN is set to: ${GH_TOKEN: -2}"
#          TAG="running-staging-frontend"
#          if git rev-parse ${TAG} >/dev/null 2>&1; then
#            git tag -d ${TAG}
#          	git push --delete origin ${TAG}
#          fi
#          git tag ${TAG} ${COMMIT_SHA}
#          git push https://x-access-token:${GH_TOKEN}@github.com/kosli-dev/jira-integration-example.git ${TAG}
#          #git push origin ${TAG}
#          echo "Deployed frontend commit ${COMMIT_SHA}"

#      - name: Deploy backend
#        # We do not have a real repo so we just tag the git repo and then the
#        # simulate-environment-reporting-staging.yml will start reporting that
#        # this environment is now running.
#        run: |
#          COMMIT_SHA=$(jq -r '.[] | select(.name == "backend") | .git_commit' /tmp/dev-env.json)
#          TAG="running-staging-backend"
#          if git rev-parse ${TAG} >/dev/null 2>&1; then
#            git tag -d ${TAG}
#          	git push --delete origin ${TAG}
#          fi
#          git tag ${TAG} ${COMMIT_SHA}
#          git push origin ${TAG}
#          echo "Deployed backend commit ${COMMIT_SHA}"
