name: Deploy to Staging

on:
  push:
    tags:
      - staging-*


jobs:
  deploy-to-staging:
    name: Simulate deployment to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}  # Checks out the tag that triggered the workflow

      - name: Tag repo
        # We do not have a real repo so we just tag the git repo and then the
        # simulate-environment-reporting-staging.yml will start reporting that
        # this environment is now running.
        run: |
          if git rev-parse running-staging >/dev/null 2>&1; then \
          	git tag -d running-staging; \
          	git push --delete origin running-staging; \
          fi
          git tag running-staging
          git push origin running-staging
