# Example workflow using the jira-release action
name: Generate Jira Release

on:
  workflow_dispatch:

jobs:
  generate-jira-release:
    name: Create or update Jira release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      -  uses: ./.github/actions/generate-jira-release
         with:
           kosli-org: ${{ vars.KOSLI_ORG }}
           kosli-flow: "jira-example-release"
           kosli-template-file: "kosli-flow-templates/release-template.yml"
           kosli-env-staging: ${{ vars.KOSLI_ENV_STAGING }}
           kosli-env-prod: ${{ vars.KOSLI_ENV_PROD }}
           kosli-flow-source: "jira-example-source"
           kosli-cli-version: ${{ vars.KOSLI_CLI_VERSION }}
           kosli-api-token: ${{ secrets.KOSLI_PUBLIC_API_TOKEN }}
           jira-base-url: ${{ vars.JIRA_BASE_URL }}
           jira-username: ${{ secrets.KOSLI_JIRA_USERNAME }}
           jira-project-id: ${{ vars.JIRA_PROJECT_ID }}
           jira-project-key: ${{ vars.JIRA_PROJECT_KEY }}
           jira-api-token: ${{ secrets.KOSLI_JIRA_API_TOKEN }}
