name: Get project Id

on:
  workflow_dispatch:
    inputs:
      project-key:
        description: 'Project key. Something like: OPS'
        required: true
        type: string

env:
  # kosli commands picks up org, flow, trail and api-token from these environment variables
  KOSLI_ORG: "${{ vars.KOSLI_ORG }}"
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
  KOSLI_CLI_VERSION: "${{ vars.KOSLI_CLI_VERSION }}"
  KOSLI_ENV_DEV: "${{ vars.KOSLI_ENV_DEV }}"
  KOSLI_ENV_STAGING:  "${{ vars.KOSLI_ENV_STAGING }}"
  KOSLI_ENV_PROD:  "${{ vars.KOSLI_ENV_PROD }}"
  # KOSLI_DRY_RUN: true
  JIRA_BASE_URL: "${{ vars.JIRA_BASE_URL }}"
  JIRA_USERNAME: ${{ secrets.KOSLI_JIRA_USERNAME }}
  JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}

jobs:
  get-project-id:
    name: Get project id
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      ### flows ###
      - name: get project id
        run: |
          set -x
          source scripts/lib-jira.sh
          echo A
          get_project_id ${{ inputs.project-key }}
          echo B
          get_project_id OPS
          echo C
          ID=$(get_project_id ${{ inputs.project-key }})
          echo " ${{ inputs.project-key }} : $ID" >> $GITHUB_STEP_SUMMARY
          
          
