name: Report development snapshot

# On a normal setup the backend and frontend built in the two build jobs would
# deploy the two artifacts to a server, and we would have set up reporting
# of the environment to kosli. In this example we do not have a server so
# we just simulate that we deploy to development

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (smallest possible)

env:
  # kosli commands picks up org, env, trail and api-token from these environment variables
  KOSLI_ORG: kosli-public
  KOSLI_ENV: jira-integration-example-dev
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
  KOSLI_CLI_VERSION: "2.11.8"

jobs:
  report-snapshot:
    name: Report development snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ env.KOSLI_CLI_VERSION }}

      - name: Report snapshot
        shell: bash
        run: |
          kosli snapshot paths ${{ env.KOSLI_ENV }} \
	        --paths-file server-paths-file.yml
