name: Report staging snapshot

# On a normal setup the backend and frontend built in the two build jobs would
# deploy the two artifacts to a server, and we would have set up reporting
# of the environment to kosli. In this example we do not have a server so
# we just simulate that we have deployed to staging

on:
  schedule:
    - cron: '55 * * * *'  # Runs 5 minutes before the start of every hour
  workflow_dispatch:

env:
  # kosli commands picks up org, env, trail and api-token from these environment variables
#  KOSLI_ORG: kosli-public
  KOSLI_ENV: "${{ env.KOSLI_ENV_STAGING }}"   # jira-integration-example-staging
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
#  KOSLI_CLI_VERSION: "2.11.8"

jobs:
  report-snapshot:
    name: Report staging snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ env.KOSLI_CLI_VERSION }}

      - name: Report snapshot
        run: |
          mkdir -p running
          git checkout running-staging-frontend
          cp -r apps/frontend running/
          git checkout running-staging-backend
          cp -r apps/backend running/
          
          kosli snapshot paths ${{ env.KOSLI_ENV }} \
            --paths-file server-paths-file.yml
