name: Update release candidate

on:
  workflow_dispatch:

env:
  # kosli commands picks up org, flow, trail and api-token from these environment variables
  KOSLI_ORG: kosli-public
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
  KOSLI_FLOW: "jira-example-release"
  KOSLI_CLI_VERSION: "2.11.8"
  KOSLI_ENV_STAGING: "jira-integration-example-staging"
  KOSLI_ENV_PROD: "jira-integration-example-prod"
  KOSLI_FLOW_SOURCE: "jira-example-source"
  # KOSLI_DRY_RUN: true
  JIRA_BASE_URL: "https://kosli-team.atlassian.net"
  JIRA_USERNAME: ${{ secrets.KOSLI_JIRA_USERNAME }}
  JIRA_API_TOKEN: ${{ secrets.KOSLI_JIRA_API_TOKEN }}
  JIRA_PROJECT_ID: 10000


jobs:
  update-candidate:
    name: Update candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ env.KOSLI_CLI_VERSION }}

      - name: Update Jira release candidate
        run: |          
          source scripts/lib-jira.sh
          source scripts/lib-kosli.sh

          # Fail if release does not exists
          CURRENT_REL_JSON=$(get_current_release_candidate ${{ env.JIRA_PROJECT_ID }})
          REL_VALUES_JSON=$(echo "${CURRENT_REL_JSON}" | jq .values)
          if [ "${REL_VALUES_JSON}" == "[]" ]; then
            echo "No release candidate exist: ${CURRENT_REL_JSON}"
            exit 1
          fi
          
          RELEASE_ID=$(echo "${REL_VALUES_JSON}" |  jq -r '.[0].id')
          echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV
          echo "Updated Jira release_id: ${RELEASE_ID}" >> $GITHUB_STEP_SUMMARY

      - name: Report current staging SW
        run: |
          source scripts/lib-kosli.sh
          get_current_running_env_json ${{ env.KOSLI_ENV_STAGING }} > /tmp/staging-env.json
          jq '[.[] | {name, fingerprint, git_commit}]' /tmp/staging-env.json > /tmp/user-data.json
          kosli attest generic \
            --name staging-software \
            --trail ${{ env.RELEASE_ID }} \
            --user-data /tmp/user-data.json
          echo "Current staging SW:" >> $GITHUB_STEP_SUMMARY
          cat /tmp/user-data.json | jq >> $GITHUB_STEP_SUMMARY


      - name: Add Jira issues to release
        run: |          
          source scripts/lib-jira.sh
          source scripts/lib-kosli.sh

          JIRA_KEYS_IN_REL=($(get_issue_keys_in_release ${{ env.RELEASE_ID }}))
          JIRA_KEYS_IN_KOSLI=($(get_issue_keys_between_staging_and_prod))

          # Add all new jira issues between prod and staging
          echo "Adding Jira issues:"  >> $GITHUB_STEP_SUMMARY
          for JIRA_KEY in ${JIRA_KEYS_IN_KOSLI[@]}; do
            if [[ ! " ${JIRA_KEYS_IN_REL[@]} " =~ " ${JIRA_KEY} " ]]; then
              add_issue_to_release ${JIRA_KEY} ${{ env.RELEASE_ID }}
              echo ${JIRA_KEY} >> $GITHUB_STEP_SUMMARY
            fi
          done
